#ifndef MACGONUTS_TEST_MACGONUTS_MEMGLOB_TESTS_H
#define MACGONUTS_TEST_MACGONUTS_MEMGLOB_TESTS_H 1

#include <cutest.h>

CUTE_DECLARE_TEST_CASE(macgonuts_memglob_tests);

#endif // MACGONUTS_TEST_MACGONUTS_MEMGLOB_TESTS_H
