.TH macgonuts 1 "January 17, 2023" "version v1" "USER COMMANDS"
.SH NAME
macgonuts \- an ARP/NDP swiss army knife to make MAC addresses going nuts on networks around!
.SH SYNOPSIS
.B macgonuts [\fIOPTIONS\fR]
.SH DESCRIPTION
\fIMacgonuts\fR is an \fIARP/NDS\fR swiss army knife to make \fIMAC addresses\fR going nuts on networks around!
.PP
It supports \fIIPv4/ARP\fR and \fIIPv6/NDP\fR.  It intends to bring you all in a shell. Anything related to
spoofing layer-2 addresses can be done elegantly with a single f_cking nice \fRnon-scripted\fR tool, a
badass executable without clumsy zillions of dependencies. Suckless is the key here.
.PP
To learn more deeply about each implemented \fImacgonuts\fR command you should read the user's manual probably
installed in:
.PP
\fI/usr/local/share/macgonuts/doc/MANUAL\fR (or equivalent in your system).
.PP
For a quick start you should give \fImacgonuts help\fR a try.
.SH EXIT STATUS
If the execution succeeds \fImacgonuts\fR returns zero, otherwise non zero values will be returned.

.PP
.SH
SEE ALSO
.TP
\fI/usr/local/share/macgonuts/doc\fR (or equivalent in your system).
.PP
You can also access a fresher on-line help at:

\fIhttps://github.com/rafael-santiago/macgonuts/blob/main/doc/MANUAL.md\fR
.PP
.SH
HOMEPAGE
.TP
https://github.com/rafael-santiago/macgonuts
.SH AUTHOR
Rafael Santiago
