on: push
name: Macgonuts CI
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install basic tools
      shell: bash
      run: |
        sudo apt-get install -y git
        sudo apt-get install -y gcc-9
        sudo apt-get update
        sudo apt-get install -y perl
        sudo apt-get install -y lcov
        sudo apt-get install -y golang-go
        sudo apt-get install -y python3
        sudo apt-get install -y python3-dev
        pip install cython
    - name: Install Hefesto
      shell: bash
      run: |
        git clone https://github.com/rafael-santiago/hefesto --recursive
        cd hefesto/src
        printf "\n" > blau.txt
        sudo ./build.sh < blau.txt
        echo "HEFESTO_INCLUDES_HOME=/usr/local/share/hefesto/include" >> "$GITHUB_ENV"
        echo "HEFESTO_MODULES_HOME=/usr/local/share/hefesto/module" >> "$GITHUB_ENV"
        sudo chown -R $USER /usr/local/share/hefesto
        cd ../..
        rm -rf hefesto
    - name: Install lcov-generator
      shell: bash
      run: |
        git clone https://github.com/rafael-santiago/helios
        cd helios
        sudo -E hefesto --install=lcov-generator
        sudo chown -R $USER /usr/local/share/hefesto
        cd ../
        rm -rf helios
    - name: Clone project repo
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Invoke Hefesto (coverage build)
      shell: bash
      run: |
        cd src
        sudo -E hefesto --coverage
    - name: Invoke Hefesto (binds build)
      shell: bash
      run: |
        cd src
        sudo -E hefesto --with-pybind --with-gobind
    - name: Tar coverage report
      shell: bash
      run: |
        sudo tar -cvf /home/libmacgonuts-coverage.tar src/reports/macgonuts-static-lib
        sudo chown $USER /home/libmacgonuts-coverage.tar
    - name: Upload LCOV results
      uses: actions/upload-artifact@v2
      with:
        name: libmacgonuts-coverage-report
        path: /home/libmacgonuts-coverage.tar
        retention-days: 7
    - name: Commit and push coverage info when needed
      shell: bash
      run: |
        git config --global user.name "GooGooMockCIBot"
        git config --global user.email "googoomockcibot@users.noreply.github.com"
        git diff --exit-code --quiet README.md || \
         (git commit -am "Automated coverage update";git push origin ${{ github.ref_name }})
  FreeBSD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build
      uses: cross-platform-actions/action@v0.15.0
      with:
        operating_system: freebsd
        version: '13.2'
        shell: bash
        memory: 1G
        cpu_count: 8
        run: |
            sudo pkg install -y git
            sudo pkg install -y go
            sudo pkg install -y python3
            sudo ln -sf `which python3` /usr/local/bin/python
            git clone https://github.com/pypa/pip
            sudo pkg install -y py39-pip
            sudo pip install cython
            echo ========================
            echo === Installing Hefesto =
            echo ========================
            git clone https://github.com/rafael-santiago/hefesto --recursive
            cd hefesto/src
            printf "\n" > blau.txt
            sudo ./build.sh < blau.txt
            sudo chown -R $USER /usr/local/share/hefesto
            HEFESTO_INCLUDES_HOME="/usr/local/share/hefesto/include"; export HEFESTO_INCLUDES_HOME
            HEFESTO_MODULES_HOME="/usr/local/share/hefesto/module"; export HEFESTO_MODULES_HOME
            cd ../..
            rm -rf hefesto
            echo ===============================
            echo === Installing lcov-generator =
            echo ===============================
            git clone https://github.com/rafael-santiago/helios --recursive
            cd helios
            sudo -E hefesto --install=lcov-generator
            sudo chown -R $USER /usr/local/share/hefesto
            cd ..
            rm -rf helios
            cd src
            sudo -E hefesto --with-pybind --with-gobind
            cd ../..
            sudo rm -rf macgonuts
